/**
 * TOMATO STRIKE — weapon roster.
 *
 * The whole armory, Temu-CS style: every gun is a vegetable with a grudge.
 * Stats are tuned against a 100 HP pool, meter/second world, and degree-based
 * spread. `headMult` is applied before armor; see core/rules.ts for the damage
 * pipeline. Balance intent noted per weapon.
 */
import type { WeaponDef, WeaponId, InventoryItem } from "./types";

export const WEAPONS: Record<WeaponId, WeaponDef> = {
  // --- Melee -----------------------------------------------------------------
  garden_trowel: {
    id: "garden_trowel",
    name: "Garden Trowel",
    slot: "melee",
    price: 0,
    killReward: 1500,
    damage: 48,
    headMult: 1.6,
    rpm: 120,
    mag: 1,
    reserve: 0,
    reloadTime: 0,
    pellets: 1,
    spread: 0,
    recoil: 0,
    falloff: 1,
    falloffEnd: 2,
    range: 1.6,
    penetration: 0,
    moveScale: 1.07,
    auto: false,
    blurb: "Free, fast, and humiliating. A back-stab plants you face-first in the mulch.",
  },

  // --- Pistols (secondary) ---------------------------------------------------
  pea_shooter: {
    id: "pea_shooter",
    name: "Pea Shooter",
    slot: "secondary",
    price: 0,
    killReward: 300,
    damage: 25,
    headMult: 3.6,
    rpm: 400,
    mag: 20,
    reserve: 120,
    reloadTime: 2.2,
    pellets: 1,
    spread: 1.5,
    recoil: 1.1,
    falloff: 0.6,
    falloffEnd: 35,
    range: 70,
    penetration: 0,
    moveScale: 1.0,
    auto: false,
    blurb: "Standard-issue spud spitter. Won't win you a medal, but it's always there.",
  },
  seed_magnum: {
    id: "seed_magnum",
    name: "Seed Magnum",
    slot: "secondary",
    price: 700,
    killReward: 300,
    damage: 58,
    headMult: 4,
    rpm: 267,
    mag: 7,
    reserve: 35,
    reloadTime: 2.2,
    pellets: 1,
    spread: 2.2,
    recoil: 3.6,
    armorPen: 0.35,
    falloff: 0.78,
    falloffEnd: 40,
    range: 90,
    penetration: 1,
    moveScale: 0.98,
    auto: false,
    blurb: "A pip the size of your fist, fired at sound-barrier speeds. One-taps melons.",
  },

  // --- SMG / Shotgun ---------------------------------------------------------
  pepper_spray: {
    id: "pepper_spray",
    name: "Pepper Spray",
    slot: "primary",
    price: 1200,
    killReward: 600,
    damage: 22,
    headMult: 3.4,
    rpm: 800,
    mag: 30,
    reserve: 120,
    reloadTime: 2.0,
    pellets: 1,
    spread: 2.4,
    recoil: 1.7,
    falloff: 0.55,
    falloffEnd: 26,
    range: 55,
    penetration: 0,
    moveScale: 1.03,
    auto: true,
    blurb: "A jalapeño firehose. Cheap, spicy, and a riot up close. Eco-round royalty.",
  },
  corn_cob: {
    id: "corn_cob",
    name: "Corn Cob",
    slot: "primary",
    price: 1200,
    killReward: 900,
    damage: 23,
    headMult: 2.2,
    rpm: 88,
    mag: 7,
    reserve: 32,
    reloadTime: 3.0,
    pellets: 8,
    spread: 6.5,
    recoil: 5,
    falloff: 0.25,
    falloffEnd: 16,
    range: 28,
    penetration: 0,
    moveScale: 0.99,
    auto: false,
    blurb: "Eight kernels of buckshot per trigger pull. Hug your enemies. Then unhug them.",
  },

  // --- Rifles ----------------------------------------------------------------
  cobb_47: {
    id: "cobb_47",
    name: "Cobb-47",
    slot: "primary",
    price: 2700,
    killReward: 300,
    damage: 36,
    headMult: 4,
    rpm: 600,
    mag: 30,
    reserve: 90,
    reloadTime: 2.5,
    pellets: 1,
    spread: 2.0,
    recoil: 2.7,
    falloff: 0.78,
    falloffEnd: 60,
    range: 110,
    penetration: 2,
    moveScale: 0.95,
    auto: true,
    teams: ["spoilers", "guard"],
    blurb: "The Spoilers' beloved corn-cob rifle. Punchy, cheap-ish, one-taps bare heads.",
  },
  m4_carrot: {
    id: "m4_carrot",
    name: "M4-Carrot",
    slot: "primary",
    price: 3100,
    killReward: 300,
    damage: 33,
    headMult: 4,
    rpm: 666,
    mag: 30,
    reserve: 90,
    reloadTime: 3.1,
    pellets: 1,
    spread: 1.7,
    recoil: 2.1,
    falloff: 0.82,
    falloffEnd: 65,
    range: 115,
    penetration: 2,
    moveScale: 0.95,
    teams: ["guard", "spoilers"],
    auto: true,
    blurb: "Garden Guard's precision carrot. Smoother recoil, kinder to your wallet's helmet.",
  },
  cucumber_cannon: {
    id: "cucumber_cannon",
    name: "Cucumber Cannon",
    slot: "primary",
    price: 4750,
    killReward: 100,
    damage: 117,
    headMult: 1.3,
    rpm: 41,
    mag: 5,
    reserve: 30,
    reloadTime: 3.7,
    pellets: 1,
    spread: 0.25,
    recoil: 9,
    armorPen: 0.9,
    falloff: 0.95,
    falloffEnd: 120,
    range: 220,
    penetration: 3,
    moveScale: 0.86,
    auto: false,
    blurb: "A scoped cucumber railgun. One body shot, one corpse. Miss and you're salad.",
  },

  // --- Grenades --------------------------------------------------------------
  rotten_lobber: {
    id: "rotten_lobber",
    name: "Rotten Lobber",
    slot: "grenade",
    price: 300,
    killReward: 300,
    damage: 128,
    headMult: 1,
    rpm: 40,
    mag: 1,
    reserve: 0,
    reloadTime: 0,
    pellets: 1,
    spread: 0,
    recoil: 0,
    falloff: 0,
    falloffEnd: 6,
    range: 30,
    penetration: 0,
    moveScale: 1.0,
    auto: false,
    blastRadius: 6,
    blurb: "A grenade-ripe tomato. Explodes into a fine, lethal marinara on impact.",
  },
  onion_bomb: {
    id: "onion_bomb",
    name: "Onion Bomb",
    slot: "grenade",
    price: 200,
    killReward: 0,
    damage: 1,
    headMult: 1,
    rpm: 40,
    mag: 1,
    reserve: 0,
    reloadTime: 0,
    pellets: 1,
    spread: 0,
    recoil: 0,
    falloff: 0,
    falloffEnd: 9,
    range: 30,
    penetration: 0,
    moveScale: 1.0,
    auto: false,
    blastRadius: 9,
    blurb: "Bursts in a cloud of weaponized tears. Anyone looking goes blind and weepy.",
  },
  compost_cloud: {
    id: "compost_cloud",
    name: "Compost Cloud",
    slot: "grenade",
    price: 300,
    killReward: 0,
    damage: 0,
    headMult: 1,
    rpm: 40,
    mag: 1,
    reserve: 0,
    reloadTime: 0,
    pellets: 1,
    spread: 0,
    recoil: 0,
    falloff: 0,
    falloffEnd: 5,
    range: 30,
    penetration: 0,
    moveScale: 1.0,
    auto: false,
    blastRadius: 5,
    blurb: "A billowing wall of pungent compost fog. Blocks sight lines, ruins picnics.",
  },
};

/** All weapons as an array, handy for menus. */
export const WEAPON_LIST: WeaponDef[] = Object.values(WEAPONS);

export function getWeapon(id: WeaponId): WeaponDef {
  return WEAPONS[id];
}

/** Buy-menu groupings (order matters for the UI columns). */
export const BUY_CATEGORIES: { label: string; key: string; items: WeaponId[] }[] = [
  { label: "Sidearms", key: "pistols", items: ["pea_shooter", "seed_magnum"] },
  { label: "Mid-Tier", key: "mid", items: ["pepper_spray", "corn_cob"] },
  { label: "Rifles", key: "rifles", items: ["cobb_47", "m4_carrot", "cucumber_cannon"] },
  { label: "Throwables", key: "nades", items: ["rotten_lobber", "onion_bomb", "compost_cloud"] },
];

/** Equipment (non-weapon) buy options. */
export interface EquipmentDef {
  key: "armor" | "armorhelmet" | "defusekit";
  name: string;
  price: number;
  blurb: string;
  /** Restrict to a team (defuse kit → guard). */
  team?: import("./types").TeamId;
}

export const EQUIPMENT: EquipmentDef[] = [
  { key: "armor", name: "Crouton Vest", price: 650, blurb: "Toasted-bread kevlar. Soaks half the splat." },
  {
    key: "armorhelmet",
    name: "Crouton Vest + Leaf Helmet",
    price: 1000,
    blurb: "Vest plus a lettuce-leaf lid. Survive the headshot, mostly.",
  },
  {
    key: "defusekit",
    name: "Defuse Kit",
    price: 400,
    blurb: "Tiny shears. Snip the Salsa Bomb's fuse in half the time.",
    team: "guard",
  },
];

/** The loadout every player respawns with for free. */
export function defaultInventory(): InventoryItem[] {
  return [
    { id: "garden_trowel", ammo: 1, reserve: 0 },
    { id: "pea_shooter", ammo: WEAPONS.pea_shooter.mag, reserve: WEAPONS.pea_shooter.reserve },
  ];
}
